config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'home/about'
  
  post "/" => "home#index"

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    if params[:id] == ""
      @nothing = "Error: You didn't type a symbol."
    elsif params[:id]
      @stock = StockQuote::Stock.quote(params[:id])
      if @stock == nil
        @error = "That stock ticker symbol doesn't exist. Please try again."
      end
    end
    
  end
  
  def about
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  
  respond_to :html

  def index
    @stock = Stock.new
    @stocks = Stock.all
    respond_with(@stocks)
  end

  def show
    respond_with(@stock)
  end

  def new
    @stock = Stock.new
    respond_with(@stock)
  end

  def edit
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.save
    respond_with(@stock)
  end

  def update
    @stock.update(stock_params)
    respond_with(@stock)
  end

  def destroy
    @stock.destroy
    respond_with(@stock)
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
  
    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not Authorized to edit this stock." if @ticker.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stock Market App", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", home_about_path %></li>
      </ul>
            
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
        <li><%= link_to "My Stock List", stocks_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        
        
        
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>





 

app/views/home/about.html.erb
<h1>About us</h1>
<p>this is my first app</p>

app/views/home/index.html.erb
<h1>Stock Market App</h1>
<p>Lookup any stock, by typing in the Company ticker symbol:</p>

<%= form_tag root_path, :method => 'POST' do %>
  <div class="form-group">
    <%= text_field_tag 'id', nil, placeholder: 'Enter Company Ticker Symbol', size: 50 %>
    <%= submit_tag 'Submit', class:'btn btn-default' %>
  </div> 
<% end %>

</br>

<% if @stock %>
<b>Company Name: </b> <%= @stock.company_name %> </br>
<b>Symbol: </b> <%= @stock.symbol %> </br>
<b>Sector: </b> <%= @stock.sector %> </br>
<b>Primary exchange: </b> <%= @stock.primary_exchange %> </br>
<b>Market cap: </b> <%= @stock.market_cap %> </br>
<b>Latest price: </b> <%= @stock.latest_price %> </br>
<b>Opening price: </b> <%= @stock.open %> </br>
<b>Highest price this year: </b> <%= @stock.week52_high %> </br>
<b>Lowest price this year: </b> <%= @stock.week52_low %>
<% elsif @nothing %>
<%= @nothing %>
<% elsif @error %>
<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stock Market App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
<%= render 'home/navbar' %>
  
<div class="container">
  <%= render 'home/flash' %>
  <%= yield %>
</div>

</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :ticker, placeholder: 'Enter Company Ticker Symbol', size: 50 %> 
    <%= f.submit "Add New Stock", class:'btn btn-default btn-sm' %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>My Stock List</h1>

<br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">Add Stock to List</h4>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<br> <br>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Company Name</th>
      <th>Latest Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
        <% @stock_quote = StockQuote::Stock.quote(stock.ticker) %>
        <tr>
        <td><%= link_to stock.ticker, stock %></td>
          
        <% if @stock_quote == nil %>
         <td>Error</td> 
         <td>Error</td> 
        <% else %>
          <td><%= @stock_quote.company_name %></td> 
          <td><%= @stock_quote.latest_price %></td> 
        <% end %>
        <td><center><%= link_to 'Edit', edit_stock_path(stock), class:"btn btn-default btn-xs" %>  <%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default btn-xs" %></center></td>
    </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/stocks/new.html.erb
<h1>Add New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% @stock_quote = StockQuote::Stock.quote(@stock.ticker) %>
  
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><b><%= @stock.ticker %></b></h3>
  </div>
  <div class="panel-body">
    
    <% if @stock_quote == nil %>
         <b>Error: No stock information was found</b> 
        <% else %>
          <b>Company Name: </b> <%= @stock_quote.company_name %> </br>
          <b>Symbol: </b> <%= @stock.ticker %> </br>
          <b>Sector: </b> <%= @stock_quote.sector %> </br>
          <b>Primary exchange: </b> <%= @stock_quote.primary_exchange %> </br>
          <b>Market cap: </b> $<%= @stock_quote.market_cap %> </br>
          <b>Latest price: </b> $<%= @stock_quote.latest_price %> </br>
          <b>Opening price: </b> $<%= @stock_quote.open %> </br>
          <b>Highest price this year: </b> $<%= @stock_quote.week52_high %> </br>
          <b>Lowest price this year: </b> $<%= @stock_quote.week52_low %>
        <% end %>
    
  </div>
  <div class="panel-footer">
    <%= link_to 'Edit', edit_stock_path(@stock), class:"btn btn-default" %>
    <%= link_to 'Delete', stock_path(@stock), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" %>
    <%= link_to 'Back', stocks_path, class:"btn btn-default" %>
  </div>
</div>